export const transactionCategories = [
  "Salário",
  "Freelance",
  "Investimentos",
  "Alimentação",
  "Transporte",
  "Saúde",
  "Lazer",
  "Compras",
  "Moradia",
  "Contas e Serviços",
  "Educação",
  "Viagens",
  "Presentes",
  "Doações",
  "Outros",
] as const